# -*- coding: utf-8 -*-
"""marta_trying_to_do_lab3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18zh0w1viqV7yinUVApL1-5caYPtjYidI
"""

!git clone https://github.com/elenipapadopulos/NLP_LAB3_Datasets.git

import nltk
nltk.download('punkt_tab')
nltk.download('brown') # import the Brown corpus from NLTK
nltk.download('punkt') # import tokenizer

from nltk import ngrams

from nltk.corpus import brown

sentences = brown.sents()[:10000]
tokenized_corpus = []

for sentence in sentences:
  tokens = nltk.word_tokenize(' '.join(sentence))

  tokens = ['<s>'] + tokens + ['</s>']

  tokenized_corpus.extend(tokens)

from nltk import bigrams
from collections import defaultdict

bigram = list(bigrams(tokenized_corpus))

# build a bigram model (dictionary of counts values)
bigram_model = defaultdict(lambda: defaultdict(lambda: 0))

# count frequency of co-occurrence
for w1, w2 in bigram:
    bigram_model[w1][w2] += 1

w1 = ('there')
print(f"{w1} -> {dict(bigram_model[w1])}")

# transform counts into probabilities
for w1 in bigram_model:
    total_count = float(sum(bigram_model[w1].values()))
    for w2 in bigram_model[w1]:
        bigram_model[w1][w2] /= total_count

w1 = ('there')
print(f"{w1} -> {dict(bigram_model[w1])}")

# bigram_model[w1] is a probability distribuition over the token that follows w1

!pip install transformers

from transformers import GPT2LMHeadModel, GPT2Tokenizer
import transformers
import torch
import math
import numpy as np

from transformers import AutoTokenizer, AutoModelForCausalLM
import matplotlib.pyplot as plt
import pandas as pd

device =  "cuda:0" if torch.cuda.is_available() else "cpu"

model = "gpt2"

tokenizer = GPT2Tokenizer.from_pretrained(model)
model = GPT2LMHeadModel.from_pretrained(model, pad_token_id = tokenizer.eos_token_id).to(device)

tokenizer.pad_token = tokenizer.eos_token # set the pad to eos_token
model.config.pad_token_id = tokenizer.pad_token_id

#logits?

"""# exercise 1: build a trigram model with backoff"""

from collections import Counter, defaultdict

unigram = list(ngrams(tokenized_corpus, 1))

unigram_count = Counter(unigram) # computes the occurrences

"""**Ex.1.1**: Let's start by computing the unigram distribution: we already have the unigram counts, so what's left to do is normalizing them."""

## compute the total number of tokens
total_number_of_tokens=sum(unigram_count.values())

## create a unigram model dictionary
## key: word
## value: probability

unigram_model={}
for word in unigram_count:
    unigram_model[word]=unigram_count[word]/total_number_of_tokens

# ------- here i have modified thissssss -------
w1 = ('there',)
print(f"{w1} -> {unigram_model[w1]}")

for sentence in sentences:

  tokens = nltk.word_tokenize(' '.join(sentence))

  tokens = ['<s>', '<s>'] + tokens + ['</s>']

  tokenized_corpus.extend(tokens)

from nltk import trigrams

trigram = list(trigrams(tokenized_corpus))

# let's define the trigram model as a dictionary of dictionaries
trigram_model = defaultdict(lambda: defaultdict(lambda: 0))

"""**Ex 1.2**: Compute co-occurrences counts. Note that the dictionary trigram_model takes as input a tuple of words as you can see from the example in the cell."""

## Ex 1.2

## compute trigram counts
trigram_count = Counter(trigram)
for w1, w2, w3 in trigram:
    trigram_model[(w1, w2)][w3] += 1

w1_w2 = ('there', 'were')
print(f"{w1_w2} -> {dict(trigram_model[w1_w2])}")

"""**Ex 1.3**: Compute trigram probabilities by normalizing counts."""

## Ex 1.3

## compute trigram probabilities
for w1_w2 in trigram_model:
    total_count=float(sum(trigram_model[w1_w2].values()))
    if total_count>0:  # Add this check
        for w3 in trigram_model[w1_w2]:
            trigram_model[w1_w2][w3]=trigram_model[w1_w2][w3]/total_count
    else:
        for w3 in trigram_model[w1_w2]:
            trigram_model[w1_w2][w3]=0

w1_w2 = ('there', 'were')
print(f"{w1_w2} -> {dict(trigram_model[w1_w2])}")

"""**Ex. 1.4** Implement the back-off function.

The function backoff should take as input the trigram, bigram and unigram models and the context words $w_1$ and $w_2$ and it should return the next word $w_3$ to be generated and its probabilty.


Recall: for each $w_3$, if $P(w_3 \mid w_1, w_2)$ is not in the trigram model, then use $P(w_3 \mid w_2)$. If there is no $P(w_3 \mid w_2)$, then use $P(w_3)$.
"""

def backoff(trigram_model, bigram_model, unigram_model, w1, w2):

  # given the context w1_w2, use backoff to find word with the highest probability:
  # for every w in vocabulary, check if p(w|w1_w2) exists, otherwise back off to bigrams
  # if there is no p(w|w2), then back off to unigram probability

  # use the computed trigram, bigram and unigram models

  # greedy decoding: you should return next_word, probability

  w1_w2=(w1,w2)
  for w3 in trigram_model[w1_w2]:
    if trigram_model[w1_w2][w3] > 0:
      return w3, trigram_model[w1_w2][w3]
    else:
      if bigram_model[w2][w3] > 0:
        return w3, bigram_model[w2][w3]
      else:
        return w3, unigram_model[w3]

def backoff(trigram_model, bigram_model, unigram_model, w1, w2):
    w1_w2=(w1, w2)

    if w1_w2 in trigram_model and trigram_model[w1_w2]:
        w3=max(trigram_model[w1_w2], key=lambda w: trigram_model[w1_w2][w])
        return w3, trigram_model[w1_w2][w3]

    if w2 in bigram_model and bigram_model[w2]:
        w3=max(bigram_model[w2], key=lambda w: bigram_model[w2][w])
        return w3, bigram_model[w2][w3]

    if unigram_model:
        w3=max(unigram_model, key=lambda w: unigram_model[w])
        return w3, unigram_model[w3]

    return None, 0

def backoff_generation(trigram_model, bigram_model, unigram_model, seed_words, max_lenght=15):

  w1, w2 = seed_words
  generated_words = [w1, w2]

  log_prob_sum = 0.0
  N = 0

  for _ in range(max_lenght):

    next_word, probability = backoff(trigram_model, bigram_model, unigram_model, w1, w2)

    generated_words.append(next_word)
    log_prob_sum += math.log(probability)
    N += 1

    w1, w2 = w2, next_word

  perplexity = math.exp(-log_prob_sum / N) if N > 0 else float('inf')

  return ' '.join(generated_words), perplexity

seed = ("they", "care")
generated_sentence, perplexity = backoff_generation(trigram_model, bigram_model, unigram_model, seed)
print("Generated sentence:", generated_sentence)
print("Perplexity:", perplexity)

seed = ("there", "was")
generated_sentence, perplexity = backoff_generation(trigram_model, bigram_model, unigram_model, seed)
print("Generated sentence:", generated_sentence)
print("Perplexity:", perplexity)

"""### Ex. 2: typo detection"""

df = pd.read_csv("/content/NLP_LAB3_Datasets/typo_dataset1.csv")

model_name = "gpt2"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(model_name)

"""We will use the token \<s> as our marker for the beginning of a sentence. First, we need to add it to the tokenizer’s vocabulary, then set it as the bos_token, and finally, resize the model’s embedding size."""

bos_token = "<s>"
tokenizer.add_tokens([bos_token])
tokenizer.bos_token = bos_token
model.resize_token_embeddings(len(tokenizer))

"""**Ex 3.1** Write a function that returns the log-probability assigned to each generated token.

You can use the `get_next_word_probs` function as a reference, but remember that this time we’re focusing on the distribution of tokens **within** the sentence, rather than the probability distribution of the next token. You can follow the comments we left in the box to guide you in the implementation.
"""

def get_next_word_probs(model, input):
  input_ids = tokenizer.encode(input, return_tensors='pt').to(device)

  with torch.no_grad():
    logits = model(input_ids).logits.squeeze()[-1]
    # logits has shape [1, input_len, model_size]
    # we compress the size into [input_len, model_size] with squeeze()
    # we are interested in next token generation: we access only the last logit

  probabilities = torch.nn.functional.softmax(logits, dim=0) # compute probabilities using softmax
  return probabilities

  #the logit refers to the generation of following words

prefix = "My name is"
probabilities = get_next_word_probs(model, prefix)
top_token_probs, top_token_vals = torch.topk(probabilities, 10) # get the top 10 tokens with the highest probabilities

for token, prob in zip(top_token_vals, top_token_probs):
  print("%.3f" % prob.item(), tokenizer.decode(token))

  #it takes the vector seen before and computes the avg

def get_token_logprobs(sentence):
    ## tokenize the sentence, compute the output and retrieve logits
    inputs=tokenizer(sentence, return_tensors="pt")

    outputs=model(**inputs)
    logits=outputs.logits

    ## remove the logits relative to the last token: we are not interested in next token generation
    ## expected shape: (sen_len, model_size) (suggestion: use squeeze))
    logits=logits.squeeze(0)[:-1, :]  # shape: (seq_len-1, vocab_size)

    # retrieve the indices (input_ids) of the sentence
    indices=inputs["input_ids"].squeeze(0)[1:]

    # compute lo-probabilites
    log_probs=torch.nn.functional.log_softmax(logits, dim=-1)

    ## retrieve the probabilities of the tokens
    token_logprobs=log_probs[range(len(indices)), indices]

    ## convert input ids to tokens to obtain a list of tokens
    tokens=tokenizer.convert_ids_to_tokens(inputs["input_ids"].squeeze(0))[1:]

    return tokens, token_logprobs.tolist()

"""Ex 3.2 Write a function that returns the cumulative log-probability up to each token in a sentence, using the probabilities computed before.

Remind that, as we are considering log-probabilities, you should sum the individual log-probabilities of each individual token.

Hint: you could return a list of elements like (w, cumulative_probability_up_to_w)
"""

def get_cumulative_token_logprobs(sentence):
    tokens, token_logprobs=get_token_logprobs(sentence)

    cumulative_logprobs=[]
    current_sum=0

    for token, logprob in zip(tokens, token_logprobs):
        current_sum += logprob
        cumulative_logprobs.append((token, current_sum))

    return cumulative_logprobs

"""**Ex. 3.3** Write a function that determines whether a sentence contains typos or not based on the difference of log-probabilities of consecutive tokens/words. The hypothesis is that a significant drop in probability between consecutive tokens may indicate that the model did not expect that token, potentially signaling a typo.

To implement this, we can define a threshold: if the difference between the log-probabilities of consecutive tokens exceeds this threshold, we can assume the sentence likely contains a typo.

The function should take as input the sentence to be analyzed and the threshold to apply for detection and it should return 0 if the sentence is flagged as potentially containing typos or	1 if the sentence is considered correct.

In the function you should confront consecutive log-probabilities and check whether, for at least one pair, their difference is above the set threshold: in that case, classify the whole sentence as incorrect.
"""

def detect_typos(sentence, threshold=5):
    cumulative_logprobs=get_cumulative_token_logprobs(sentence)

    logprobs=[logprob for _, logprob in cumulative_logprobs]

    #the sentence has only one token > it can't have consecutive differences
    if len(logprobs) <= 1:
        return 1

    differences=[]
    for i in range(1, len(logprobs)):
        diff=logprobs[i-1]-logprobs[i]
        differences.append(diff)

    for diff in differences:
        if diff>threshold:
            return 0

    return 1

"""**Ex 3.4** Test your function experimenting with different thresholds.
Select the best threshold on the whole data and report the accuracy in the Moodle.

You should achieve an accuracy higher than 0.70.
"""

best_threshold=0
best_accuracy=0

for threshold in range(5,15):
    correct=0
    for i, row in df.iterrows():
        sentence, label=row[1], row[2]
        pred=detect_typos(sentence, threshold=threshold)
        if label==pred:
            correct+=1

    accuracy=correct/len(df)
    print(f"Threshold: {threshold}, Accuracy: {accuracy:.4f}")

    if accuracy>best_accuracy:
        best_accuracy=accuracy
        best_threshold=threshold

print(f"\nBest threshold: {best_threshold}")
print(f"Best accuracy: {best_accuracy:.4f}")

"""**Error Analysis**: in this exercise, we exploited the probability distribution of a Large Language Model to detect typos.
Did you notice any linguistic or grammatical feature that make detection more accurate? Do you think relying solely on threshold-based differences in log-probabilities is sufficient or should we use a more sophisticated and complete system? Write your comments in the box below.

### Moodle Submission

Extract the code to run exercise 3 from the notebook as a .py file (you might have to add some initial import instructions). Make sure the code runs and computes the accuracy correctly. Upload the code on the activity "Lab assignment 3" on the Moodle of the course. In the comment box on Moodle report your accuracy and your comments related to the error analys (box right above)
"""